### PR TITLE
React-based ESLint rules, enforce hook deps

### PR DESCRIPTION
**Pull request by zeppelinnn**
We were missing eslint packages here for react-based stuff incl hooks - added those in here and updated all functionality that was missing deps to have those included for hooks like usememo/usecallback

Tested by publishing an alpha version and linking in the react-sdk-demo repo, checking that existing functionality (incl onramp) works as expected (prior to this the onramp window wasn't correctly being opened when the user changed during the session.

### CODE REVIEW

**Comment by zeppelinnn** [comment]
Current dependencies on/for this PR:
* latest
  * **PR #128** <a href="https://app.graphite.dev/github/pr/fractalwagmi/react-sdk/128" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/fractalwagmi/react-sdk/128?utm_source=stack-comment).

**Review by obber — APPROVED** [review]

**Review by obber — COMMENTED** [review]
Wait - I think we could just extend the shared eslint config. Example:

https://github.com/fractalwagmi/bathhaus/blob/main/.eslintrc.json

and

https://github.com/fractalwagmi/fractal/blob/main/.eslintrc.json

**Comment by obber** [comment]
Oh but the shared eslint config is private (https://www.npmjs.com/package/@fractalwagmi/eslint-config-next)

So nevermind - we probably don't want to bring it in here.

**Comment by zeppelinnn** [comment]
yeah IIRC we talked about doing this but the eslint package is nextjs specific as well as private

**Pull request merged**
